### ISSUE TITLE
Selecting a maintainer

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G4#1]
Hi @pratibha77118 @sharmistharanit 
Who are you interested in becoming the maintainer(Keeping in mind you're active online) of this HW?

**Comment by pratibha77118** [comment]
Hi all, 
If any of you want to be maintainer I am okay with it. I have been a maintainer since last three homeworks.

**Comment by Mosaddeq107** [comment]
> Hi all, If any of you want to be maintainer I am okay with it. I have been a maintainer since last three homeworks.

Okay,
Thanks for letting us know.
Then, I will text Dr. Tim to be a maintainer.

**Comment by sharmistharanit** [comment]
Okay, so Mosaddeq will be the maintainer for our group.

**Comment by reshnashrestha** [comment]
As I see that @Mosaddeq107 is maintainer, is there anything we should be careful with except merging?
