### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G4#11]
Who is doing task 3? We can discuss on how to proced.

**Comment by reshnashrestha** [comment]
Is there any update on task 3?

**Comment by Mosaddeq107** [comment]
> Is there any update on task 3?

No, we are still in the primary stage.

**Comment by reshnashrestha** [comment]
Have you begin?

**Comment by Mosaddeq107** [comment]
> Have you begun?

I started doing this. However, I am still waiting for the completion of Task 1 and Task 2.

**Comment by reshnashrestha** [comment]
Yeah task three is kind of always depended and then we have to figure out all at last hour.

**Comment by sharmistharanit** [comment]
@Mosaddeq107 he will do task 3

**Comment by reshnashrestha** [comment]
Yeah it’s cleared on the class today
