### ISSUE TITLE
Zero in the boundary bracket

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G4#15]
Hi all,
I can see the values given in the boundary bracket as [0,10.Group number] and [0, pi.group number]. Since these intervals contains zero value which give undefined values for the function given. So, can we just avoid zero from this intervals and take interval starting from 1. Or Is there any other way to use this intervals as it is?

**Comment by reshnashrestha** [comment]
I don;t think that we can avoid zero. There could be any other alternative for this.

**Comment by pratibha77118** [comment]
@reshnashrestha I defined the the zero with the value as small as 1e-6 to avoid the zero error.
