### ISSUE TITLE
Can I use nan_to_num to define a number that approaches zero, but is not exactly zero?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework6G4#16]

**Comment by WildJimmy** [comment]
I answered this here in my group https://github.com/ubsuny/23-Homework6G1/issues/18

**Comment by Mosaddeq107** [comment]
> I answered this here in my group [ubsuny/23-Homework6G1#18](https://github.com/ubsuny/23-Homework6G1/issues/18)

Thank for the elucidation

**Comment by sharmistharanit** [comment]
Thanks so much for the clarification.
