### ISSUE TITLE
Comphys Integration

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G4#20]
What does it mean?

**Comment by tirthbha** [comment]
@reshnashrestha you mean Comphys Integration?

**Comment by reshnashrestha** [comment]
Yes. Any ideas?

**Comment by Mosaddeq107** [comment]
I think he meant it to be the Comphys repository

**Comment by sharmistharanit** [comment]
I have the same question as @reshnashrestha

**Comment by reshnashrestha** [comment]
Yeah it was explained in the class today
