### ISSUE TITLE
Function to be used for task 1

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G4#22]
Do we need to use all the functions listed on the task 1 with the three different approaches?

**Comment by Mosaddeq107** [comment]
> Do we need to use all the functions listed on the task 1 with the three different approaches?

Yes, @tirthbha 
Dr. Time mentioned it in the Discord.

**Comment by pratibha77118** [comment]
Yes @tirthbha we use all three function and compare their accuracies.
