### ISSUE TITLE
Generating calculus.py

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G4#26]
Hi, 
Can anybody tell us, if is there any template for the file **calculus.py**?

**Comment by tirthbha** [comment]
@Mosaddeq107 Yeah, you can find that in CompPhys under calculus section ( integrals.py)

**Comment by pratibha77118** [comment]
Ya I too use function defined on integral.py to create module file calculas.py

**Comment by Mosaddeq107** [comment]
> Ya I too use function defined on integral.py to create module file calculas.py

Thank you.

**Comment by Mosaddeq107** [comment]
> @Mosaddeq107 Yeah, you can find that in CompPhys under calculus section ( integrals.py)

Thank you for your suggestion.
