### ISSUE TITLE
Link inaccessible 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G4#27]
The link (https://github.com/ubsuny/CompPhys/Calculus) Dr. Tim provided in the repository is inaccessible, at least from my end. Can anybody give me the correct link?

<img width="1199" alt="Screenshot 2023-11-19 at 12 14 14 AM" src="https://github.com/ubsuny/23-Homework6G4/assets/66480280/681194be-8f11-4d7f-8030-53bb422d9ec2">

**Comment by pratibha77118** [comment]
@Mosaddeq107 yes this is not accessible. We have to go through https://github.com/ubsuny/CompPhys/tree/main/Calculus  repository to use the functions defined for sympson, trapezoid and adaptive trapezoid method.

**Comment by Mosaddeq107** [comment]
Thank you so much @pratibha77118
