### ISSUE TITLE
 Ambiguity for graph of cos(1/x)

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G4#31]
I get the graph of cos(1/x) defined from [0,4*pi] as :
![Cos1:x image](https://github.com/ubsuny/23-Homework6G4/assets/72980895/7c57be16-6a87-4fae-921c-63890474e0e2)
I doubt whether the graph I got is correct. I would appreciate if any one share the nature of graph for cos(1/x).

**Comment by tirthbha** [comment]
![cos(inverse_x)](https://github.com/ubsuny/23-Homework6G4/assets/143649367/869fb429-ac73-4cb0-95ed-ea9d073dc0e7)
I think your plot is correct but i think, it should be symmetrical about y-axis.

**Comment by pratibha77118** [comment]
I have not used any negative values of x . Thus, it might be the case that i got the graph like that.
