### ISSUE TITLE
Root finding

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G4#32]
Which algorithms have you used to find roots? Can we use Bisection and Newton-Raphson method to find roots?

**Comment by sharmistharanit** [comment]
I will use the bisection method. I have not decided the other one.

**Comment by sharmistharanit** [comment]
Which methods are you using? @tirthbha

**Comment by tirthbha** [comment]
@sharmistharanit I have tried with both methods.

**Comment by sharmistharanit** [comment]
Thanks for letting me know.
