### ISSUE TITLE
Final Task Distribution. 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G4#35]
Since @sharmistharanit has an issue doing Task 3, I will do Task 3. @pratibha77118 Will do Task 1.

**Comment by pratibha77118** [comment]
Thanks @Mosaddeq107 I will finish task 1 by tomorrow. This time we gonna do documentation of our part by ourselves.

**Comment by Mosaddeq107** [comment]
> Thanks @Mosaddeq107 I will finish task 1 by tomorrow. This time we gonna do documentation of our part by ourselves.

Did Dr Tim mention it? I thought we didn't need to do that for this HW.

**Comment by Mosaddeq107** [comment]
We will do our task as you suggested. 
I am closing this issue.
