### ISSUE TITLE
calculate the efficiency for each method

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G4#41]
I have compared the accuracy of each method with the actual integration value using scipy. Any idea how to find the efficiency of these method to give the accuracy value?

**Comment by Mosaddeq107** [comment]
Well done. But I need some time to analyse or think about this matter.

**Comment by reshnashrestha** [comment]
@pratibha77118  do you have any ideas on numpy integration and comphys integration?

**Comment by pratibha77118** [comment]
@reshnashrestha I am still not clear on that part but have done efficiency finding part for task 1.
