### ISSUE TITLE
How do we compare this part? 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G4#42]
**Task 3: Compare the numpy integration functions to the ones found in compphys**

Do we need to compare this part using documentation or a writing algorithm and analyze it numerically?

**Comment by Mosaddeq107** [comment]
@sharmistharanit, Do you have any idea, please?

**Comment by reshnashrestha** [comment]
I have the same question

**Comment by sharmistharanit** [comment]
Till now, I do not have any idea. @Mosaddeq107
