### ISSUE TITLE
Writing documentation clarified by Dr. Tim 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G4#43]
I hope it will clear up your confusion.

<img width="959" alt="Screenshot 2023-11-20 at 12 15 40 AM" src="https://github.com/ubsuny/23-Homework6G4/assets/66480280/edb3478e-fc1f-4a2b-921e-db1da9a7f52b">

**Comment by reshnashrestha** [comment]
Yeah we should be preparing documenting for each section.

**Comment by sharmistharanit** [comment]
Thank you for the clarification.
