### ISSUE TITLE
calculas.py

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework6G4#44]
Do we need to create just one python file for both task1 and 2. @pratibha77118 @Mosaddeq107

**Comment by pratibha77118** [comment]
Create a single module file to be used for your task.

**Comment by sharmistharanit** [comment]
Ok.

**Comment by sharmistharanit** [comment]
Do we need to update two module files (one from you one from me) in a single one? @sharmistharanit
