### ISSUE TITLE
Can you acccept the pull request.

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework6G4#48]

**Comment by sharmistharanit** [comment]
We can see Prathiva's work. @Mosaddeq107

**Comment by Mosaddeq107** [comment]
I can't see your pull request @sharmistharanit

**Comment by AhmedCode99** [comment]
you did not make a pull request

**Comment by AhmedCode99** [comment]
make sure that you resolve any conflicts between your code and the main branch before you create a pull request

**Comment by sharmistharanit** [comment]
ok. Thanks for clarification.
