### ISSUE TITLE
Can you share your task 1 module file? 

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework6G4#59]
@pratibha77118

**Comment by sharmistharanit** [comment]
I can include the root-finding code in calculus.py.

**Comment by pratibha77118** [comment]
@sharmistharanit  the task 1 module file has simpson, trapezoid and adaptive trapezoid method to find the integral value. It is different than the file merged here. Please have a look at it here.https://github.com/ubsuny/CompPhys/blob/main/Calculus/integrals.py

**Comment by sharmistharanit** [comment]
@Mosaddeq107 He has already updated the calculas,py file

**Comment by sharmistharanit** [comment]
Thanks @Mosaddeq107
