### ISSUE TITLE
Task 2 related

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework6G4#60]

**Comment by sharmistharanit** [comment]
I have seen that groups 1,2 and 3 used 4 methods for root finding. Are we supposed to use all of them or just two?

**Comment by sharmistharanit** [comment]
I wrote just two of them. Can anyone tell me what to do?

**Comment by sharmistharanit** [comment]
@pratibha77118 @Mosaddeq107

**Comment by s4il3sh** [comment]
> I wrote just two of them. Can anyone tell me what to do?

Yes, you are correct. We can use only 2.

**Comment by sharmistharanit** [comment]
ok. Thanks.
