### ISSUE TITLE
Check files 

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G4#61]
@Mosaddeq107 please check all the files before merging it.  There was an issue of merge conflict in earlier homework.

**Comment by Mosaddeq107** [comment]
> @Mosaddeq107 please check all the files before merging it. There was an issue of merge conflict in earlier homework.

Thanks for your suggestion. If there is any problem with the currently accepted files, please let me know.

**Comment by pratibha77118** [comment]
Sure!
