### ISSUE TITLE
task-3

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework6G4#63]
Hello all, I want to ask who is doing task 3 in your group. I have a question, I guess we need to check all the functions in the calculus.py or may be just two? I am a bit confused, because there are a lot of functions right?. Thank you

**Comment by Mosaddeq107** [comment]
> Hello all, I want to ask who is doing task 3 in your group. I have a question, I guess we need to check all the functions in the calculus.py or may be just two? I am a bit confused, because there are a lot of functions right?. Thank you

I am here. We need to do all 👍

**Comment by uarif** [comment]
Okay, thank you for the clerification.  Lets see.
