### ISSUE TITLE
Merge file for task 1

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G4#74]
@Mosaddeq107 Could you please put all the task 1 files in a folder "Task 1 "after merging my files. I cannot do that since I have files in different branches. I will send you merge request soon if in case professor does not reply my issue on managing the module file.

**Comment by pratibha77118** [comment]
@Mosaddeq107 put files on folder naming task 1, task 2 ... etc

**Comment by Mosaddeq107** [comment]
Hi @pratibha77118 
I created a folder named Task 1.
However, I am slightly confused about which files should go to the Task 1 folder since there are many files in our repo. Would you please mention those files' names here?
