### ISSUE TITLE
HW 6 documentation

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G4#9]
So the task assignment does not include the documentation part. Do we have to do that? If yes, Whose role could be it?

**Comment by poojashresthacode** [comment]
I believe, no need to do documentation.

**Comment by Mosaddeq107** [comment]
> I believe, no need to do documentation.

I think we documentation @poojashresthacode

**Comment by Mosaddeq107** [comment]
Dr. Tim commented on another issue of another group.

<img width="959" alt="Screenshot 2023-11-20 at 12 15 40 AM" src="https://github.com/ubsuny/23-Homework6G4/assets/66480280/08c7a545-a470-4eb3-a9bd-49065b29117d">

**Comment by reshnashrestha** [comment]
So we will be documenting individually task wise
